import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-linear-to-br from-purple-700 to-purple-600 relative overflow-hidden font-['Segoe_UI',Tahoma,Geneva,Verdana,sans-serif]">
          {/* Decorative circles */}
          <div className="absolute w-[200px] h-[200px] bg-white rounded-full opacity-10 top-[10%] left-[5%]"></div>
          <div className="absolute w-[150px] h-[150px] bg-[#FF9A8B] rounded-full opacity-10 bottom-[15%] left-[10%]"></div>
          <div className="absolute w-[120px] h-[120px] bg-[#4FACFE] rounded-full opacity-10 top-[15%] right-[10%]"></div>
          <div className="absolute w-[180px] h-[180px] bg-[#43E97B] rounded-full opacity-10 bottom-[10%] right-[5%]"></div>
          <div className="absolute w-[100px] h-[100px] bg-[#FA709A] rounded-full opacity-10 top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2"></div>
          {children}
        </div>
      </body>
    </html>
  );
}
